accounts/urls.py
from django.urls import path
from accounts import views

app_name='accounts'
urlpatterns = [
    path('profile/<int:category_id>/<int:page>', views.ProfileView.as_view(), name='profile'),
    path('login/', views.LoginView.as_view(), name='account_login'),
    path('logout/', views.LogoutView.as_view(), name='account_logout'),
    path('signup/', views.SignupView.as_view(), name='account_signup'),
    path('profile_create/', views.ProfileCreateView.as_view(), name='profile_create'),
]

bookdoor/urls.py
from django.urls import path
from . import views
from .views import BookDoorView, BookSearchView, BookCreateView
from .views import BookDetailView, BookCommentView, BookConditionView
from .views import FavoriteBookListView,BookRankingView
from .views import CommentSearchView

app_name='bookdoor'
urlpatterns=[
  path(r'',BookDoorView.as_view(), name='index'),
  path(r'book_condition/<int:category_id>/<int:age>',\
    BookConditionView.as_view(), name='book_condition'),
  path(r'book_search/<int:category_id>/<str:search>',BookSearchView.as_view(),\
     name='book_search'),
  path(r'book_detail/<str:book_code>',BookDetailView.as_view(), name='book_detail'),
  path(r'book_comment/<str:book_code>',BookCommentView.as_view(), name='book_comment'),
  path(r'book_comment_good/<str:code>',views.book_comment_good,name='book_comment_good'),
  path(r'book_comment_report/<str:code>',views.book_comment_report,\
     name='book_comment_report'),
  path(r'favorite_book/<str:code>',views.favorite_book,\
     name='favorite_book'),
  path(r'favorite_book_list/<int:category_id>/<str:search>',\
    FavoriteBookListView.as_view(),name='favorite_book_list'),
  path(r'book_ranking',BookRankingView.as_view(),name='book_ranking'),
  path(r'comment_search/<int:category_id>/<str:search>/<int:evaluation>',\
    CommentSearchView.as_view(),name='comment_search'),
  path(r'book_create',BookCreateView.as_view(), name='book_create'),
]

django_app_3/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookdoor.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookdoor/models.py
from django.conf import settings
from django.db import models


class Book(models.Model):
  title=models.CharField(max_length=100)
  author=models.CharField(max_length=100,blank=True, null=True)
  illustrator=models.CharField(max_length=100,blank=True, null=True)
  translator=models.CharField(max_length=100,blank=True, null=True)
  publisher=models.CharField(max_length=100,blank=True, null=True)
  category_id=models.IntegerField(blank=True, null=True)
  url=models.CharField(max_length=100,blank=True, null=True)
  code=models.CharField(max_length=10)
  evaluation=models.FloatField(default=0)
  date=models.DateField(blank=True, null=True)

  def __str__(self):
    return '<Book:id='+str(self.id)+','+\
      self.title+'('+self.author+')>'


class BookComment(models.Model):

  data=[
    (5,'5'),
    (4,'4'),
    (3,'3'),
    (2,'2'),
    (1,'1')
  ]

  book=models.ForeignKey(Book,on_delete=models.CASCADE,related_name='book')
  writer=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='writer')
  evaluation=models.IntegerField(choices=data)
  title=models.CharField(max_length=20,blank=True, null=True)
  comment=models.CharField(max_length=5000,blank=True, null=True)
  code=models.CharField(max_length=10)
  spoiler=models.BooleanField(verbose_name='',default=False)
  date=models.DateField(blank=True,null=True)
  good=models.IntegerField(default=0)
  age=models.IntegerField(default=0)
  report=models.IntegerField(default=0)
  
  def __str__(self):
    return '<BookComment:id='+str(self.id)+','+\
      str(self.writer)+'('+str(self.evaluation)+')>'

    
class BookCommentGood(models.Model):
  owner=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='book_comment_good_owner')
  comment=models.ForeignKey(BookComment,on_delete=models.CASCADE,related_name='book_comment_good_comment')
  date=models.DateField()

  def __str__(self):
    return '<BookCommentGood:id='+str(self.id)+','+\
      str(self.owner)+'('+str(self.date)+')>'


class BookCommentReport(models.Model):
  owner=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='book_comment_report_owner')
  comment=models.ForeignKey(BookComment,on_delete=models.CASCADE,related_name='book_comment_report_comment')
  date=models.DateField()

  def __str__(self):
    return '<BookCommentReport:id='+str(self.id)+','+\
      str(self.owner)+'('+str(self.date)+')>'


class FavoriteBook(models.Model):
  owner=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='favorite_book_owner')
  book=models.ForeignKey(Book,on_delete=models.CASCADE,related_name='favorite_book_book')

  def __str__(self):
    return '<FavoriteBook:id='+str(self.id)+','+\
      str(self.owner)+'>'


class Category(models.Model):
  category=models.CharField(max_length=20)

  def __str__(self):
    return '<Category:id='+str(self.id)+','+\
      str(self.category)+'>'

bookdoor/forms.py
from django import forms
from .models import BookComment
from .models import Category

class BookSearchForm(forms.Form):
  search=forms.CharField(label='',required=None)

data=[
  (1,'0'),
  (2,'1'),
  (3,'2'),
  (4,'3'),
  (5,'4')
]
class BookCommentForm(forms.ModelForm):

  evaluation = forms.ChoiceField(label='属性', widget=forms.RadioSelect(), \
    choices= data, initial=0)
  title = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder':''}))
  class Meta:
    model=BookComment
    fields=['evaluation','title','spoiler','comment']

class BookCreateForm(forms.Form):
  data=[(0,'無し')]
  for category in Category.objects.all():
    item=(category.id,category.category)
    data.append(item)

  title=forms.CharField(label='タイトル',max_length=100)
  author=forms.CharField(label='筆者',max_length=100,required=None)
  illustrator=forms.CharField(label='イラストライター',max_length=100,required=None)
  translator=forms.CharField(label='翻訳者',max_length=100,required=None)
  publisher=forms.CharField(label='出版社',max_length=100,required=None)
  category=forms.ChoiceField(label='カテゴリー',choices=data,required=None)
  url=forms.CharField(label='URL',max_length=100)
  date=forms.DateField(label='発行日',required=None)

bookdoor/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import TemplateView
from accounts.models import CustomUser ,Profile
from .models import Book, BookComment, BookCommentGood
from .models import BookCommentReport, FavoriteBook
from .models import Category
from .forms import BookSearchForm, BookCreateForm,BookCommentForm
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
import datetime
import random
import string
import numpy as np


class BookDoorView(TemplateView):
  
  def __init__(self,):
    self.params={
      'books':'',
      'comment':'',
      'attention':'',
      'category':Category.objects.all(),
      'age_range':range(15),
      'tree':'',
    }

  def get(self,request):

    def default_ranking():
      ranking=[]

      books=Book.objects.all()
      today=datetime.date.today()
      if request.user.is_authenticated:
        birthday=request.user.birthday
        age=(int(today.strftime("%Y%m%d")) - int(birthday.strftime("%Y%m%d"))) // 10000

      for book in books:
        average=0.0
        total=0
        count=0
        book_comments=BookComment.objects.filter(book=book)
        if request.user.is_authenticated:
          book_comments=BookComment.objects.filter(book=book,\
            age__gte=age-1,age__lte=age+1)
        for book_comment in book_comments:
          if (int(today.strftime("%Y%m%d")) - \
            int(book_comment.date.strftime("%Y%m%d"))) <=100:
            item=1.25
          else:
            item=1
          total+=book_comment.evaluation*item
          count+=1
        if count == 0:
          count=1
        average=total/count
        ranking.append((book.id-1,average))
      
      return sorted(ranking, key=lambda r: r[1], reverse=True)

    def first_scores(user,book_count):
      book_comments=BookComment.objects.filter(writer=user)
      item=np.zeros(book_count)
      for book_comment in book_comments:
        id=book_comment.book_id
        item[id-1]=book_comment.evaluation

      return item

    def create_scores(target_user,book_count):
      scores=[]
      scores.append(first_scores(target_user,book_count))

      users=CustomUser.objects.all()
      for user in users:
        
        if user == target_user:
          continue

        book_comments=BookComment.objects.filter(writer=user)
        if len(book_comments) == 0:
          continue

        item=np.zeros(book_count)
        for book_comment in book_comments:
          id=book_comment.book_id
          item[id-1]=book_comment.evaluation

        scores.append(item)

      return np.array(scores)

    def create_age_scores(target_user,book_count):
      scores=[]
      scores.append(first_scores(target_user,book_count))

      today=datetime.date.today()
      birthday=request.user.birthday
      age=(int(today.strftime("%Y%m%d")) - int(birthday.strftime("%Y%m%d"))) // 10000

      users=CustomUser.objects.all()
      for user in users:
        
        if user == target_user:
          continue

        book_comments=BookComment.objects.filter(writer=user,\
          age__gte=age-1,age__lte=age+1)

        if len(book_comments) == 0:
          continue

        item=np.zeros(book_count)
        for book_comment in book_comments:
          id=book_comment.book_id
          item[id-1]=book_comment.evaluation

        scores.append(item)

      return np.array(scores)

    def get_correlation_coefficents(scores, target_user_index):
      similarities = []
      target = scores[target_user_index]
      
      for i, score in enumerate(scores):
        indices = np.where((target * score ) != 0)[0]
        if len(indices) < 3 or i == target_user_index:
          continue
        
        similarity = np.corrcoef(target[indices], score[indices])[0, 1]
        if np.isnan(similarity):
          continue
    
        similarities.append((i, similarity))
      
      return sorted(similarities, key=lambda s: s[1], reverse=True)

    def predict(scores, similarities, target_user_index, target_item_index):
      target = scores[target_user_index]
      
      avg_target = np.mean(target[np.where(target > 0)])
      
      numerator = 0.0
      denominator = 0.0
      k = 0
      
      for similarity in similarities:
        if k > 5 or similarity[1] <= 0.0:
          break
            
        score = scores[similarity[0]]
        if score[target_item_index] >= 0:
          denominator += similarity[1]
          numerator += similarity[1] * (score[target_item_index] - np.mean(score[np.where(score >= 0)]))
          k += 1
              
      return avg_target + (numerator / denominator) if denominator > 0 else -1

    def rank_items(scores, similarities, target_user_index,book_count):
      rankings = []
      target = scores[target_user_index]
      for i in range(book_count):
        if target[i] >= 1:
          continue

        rankings.append((i, predict(scores, similarities, target_user_index, i)))
          
      return sorted(rankings, key=lambda r: r[1], reverse=True)

    def mean_adjustment(scores):
      scores_nan = np.copy(scores)
      scores_nan[scores_nan == 0] = np.nan
      
      adjusted_scores = np.ndarray(shape=scores_nan.shape)
      for i, score in enumerate(scores_nan):
          adjusted_scores[i] = score - np.nanmean(score)
      return np.nan_to_num(adjusted_scores)

    def item_get_cos_similarities(scores, target_item_index):
      similarities = []

      items = mean_adjustment(scores).transpose()
      target_item = items[target_item_index]
      
      for i, item in enumerate(items):
        if i == target_item_index:
          continue
            
        similarity = np.dot(target_item, item.T) / (np.linalg.norm(target_item) * np.linalg.norm(item))
        similarities.append((i, similarity))

      return sorted(similarities, key=lambda s: s[1], reverse=True)

    def item_predict(scores, similarities, target_user_index):
      numerator = 0.0
      denominator = 0.0
      k = 0
      
      target = scores[target_user_index]
      
      for similarity in similarities:

          if (k >= 5 or similarity[1] <= 0):
              break
          if (target[similarity[0]] == 0):
              continue
              
          numerator += similarity[1] * target[similarity[0]]
          denominator += similarity[1]
          k += 1
      
      return numerator / denominator if denominator != 0.0 else -1

    def item_rank_items(scores, similarities, target_user_index,book_count):
      ranking = []

      for i in range(book_count):
        if scores[target_user_index][i] > 0:
          continue
        
        similarities =  item_get_cos_similarities(scores, i)
        
        predict_score = item_predict(scores, similarities, target_user_index)
        
        ranking.append((i, predict_score))
          
      return sorted(ranking, key=lambda r: r[1], reverse=True)

    def youser_filter(ranking_origin,target_user):
      comments=BookComment.objects.filter(writer=target_user)
      number_list=[]
      ranking=[]
      for comment in comments:
        number_list.append(comment.book_id-1)

      for rank in ranking_origin:
        if rank[0] not in number_list:
          ranking.append(rank)
      
      return ranking

    if request.user.is_authenticated:
      target_user=self.request.user
      last_book = Book.objects.all().last()
      book_count = last_book.id

      scores=create_scores(target_user,book_count)
      age_scores=create_age_scores(target_user,book_count)

      target_user_index = 0
      similarities = get_correlation_coefficents(scores, target_user_index)

      if len(similarities) !=0 and similarities[0][1] > 0:
        rank = rank_items(age_scores, similarities, target_user_index,book_count)
      else:
        rank = item_rank_items(age_scores, similarities, target_user_index,book_count)
        if len(rank) == 0:
          self.params['attention'] = 1
        elif np.isnan(rank[0][1]):
          ranking_origin=default_ranking()
          rank=youser_filter(ranking_origin,target_user)
    else:
      rank=default_ranking()


    books = []

    for id in rank:
      book=Book.objects.filter(id=id[0]+1)
      if len(book) != 0:
        books.append(book[0])
        

    if len(books) == 0:
      books=Book.objects.all().order_by('date').reverse()

    comment=BookComment.objects.filter(good__gte=10,title=True,comment=True).order_by('date', 'good')
    if len(comment) < 9:
      comment=BookComment.objects.order_by('date', 'good')

    k=0
    comment_loop=[]
    for item in comment:
      if k >= 9:
        break
      if item.comment != None and item.title != None:
        profile=Profile.objects.get(owner=item.writer)
        nickname=profile.nickname
        item.nickname=nickname
        comment_loop.append(item)
        k+=1

    comment_set=[]
    for i in range(len(comment_loop)//3):
      item={}
      item['a']=comment_loop[i*3]
      item['b']=comment_loop[i*3+1]
      item['c']=comment_loop[i*3+2]
      comment_set.append(item)

    if request.user.is_authenticated:
      tree=BookComment.objects.filter(writer=self.request.user).count()
      if tree<10:
        tree=1
      elif tree<20:
        tree=2
      elif tree<35:
        tree=3
      elif tree<50:
        tree=4
      elif tree<75:
        tree=5
      elif tree<100:
        tree=6
      else:
        last=BookComment.objects.filter(writer=self.request.user).last()
        today=datetime.date.today()
        ago=(int(today.strftime("%Y%m%d")) - int(last.date.strftime("%Y%m%d")))
        if ago<30:
          tree=7
        else:
          tree=8
    else:
      tree=1

    self.params['tree']=tree
    self.params['comment']=comment_set
    self.params['books']=books
    return render(request,'bookdoor/index.html', self.params)

  def post(self,request):

bookdoor/templates/bookdoor/book_create.html
{% extends 'bookdoor/layout.html' %}

{% block title %}Book_Create{% endblock %}

{% block content %}
<div>
  <div>
    <form  method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="create" >
    </form>
  </div>
</div>
{% endblock %}

bookdoor/templates/bookdoor/book_detail.html
{% extends 'bookdoor/layout.html' %}
{% load static %}

{% block head %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta name="description" content="" />
<meta name="author" content="" />
<title>Small Business - Start Bootstrap Template</title>
<!-- Favicon-->
<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
<!-- Core theme CSS (includes Bootstrap)-->

<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'bookdoor/css/book_detail.css' %}">
{% endblock %}

{% block content %}
<div class="container px-2 px-lg-5 py-1 my-4">
  <!-- Heading Row-->
  <div class="row gx-4 gx-lg-5 mt-5 mb-2">
    <div class="col-lg-3">
      <h3>{{ book.title }}</h3>
      <div class="author_item">
        {% if book.author != '' %}
        <h5 class="author">{{ book.author}}(著)</h5>
        {% endif %}
        {% if book.illustrator != '' %}
        <h5 class="author">{{ book.illustrator}}(イラスト)</h5>
        {% endif %}
        {% if book.translator != '' %}
        <h5 class="author">{{ book.translator }}(翻訳)</h5>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="row gx-4 gx-lg-5 align-items-center ">
    <div class="col-lg-3 bg-white py-3 mt-0 align-self-start">
      <div class="example">
        <a href="{{ book.url }}">
          <img class="img-fluid rounded" src="https://m.media-amazon.com/images/I/417V0YU0LEL._SL500_.jpg" alt="..." />
        </a>
        <button class="btn btn-warning btn-circle m-1"><i class="far fa-star"></i></button>
      </div>
      <a href="{% url 'bookdoor:book_comment' book.code %}"><button class="col btn btn-green-moon btn-rounded">ほんをよんだ</button></a>
      <a href="{% url 'bookdoor:favorite_book' book.code %}">
        <button class="col btn btn-green-fav btn-rounded">
          {% if count == 0 %}
          おきにいり
          {% else %}
          おきにいりをはずす
          {% endif %}
        </button>
      </a>
    </div>

    <div class="col-lg-8 bg-white py-3 ml-lg-5">
      <h2>コメント・感想</h2>
      <!-- <div class="btn-group">
        <button type="button" class="btn  dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          コメント順番
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">人気順</a>
          <a class="dropdown-item" href="#">新しい順</a>
        </div>
      </div> -->
      <div class="border-bottom mb-2">
        <select class="form-control">
          <option>人気順</option>
          <option>新しい順</option>
        </select>
      </div>
      
      {% for item in comment %}
      <!-- <div>
      <a href="{% url 'bookdoor:book_comment_report' item.code %}">
        通報
        {% if item.count_report == 0 %}未
        {% else %}済
        {% endif %}
        </a>
      </div>  -->
      <div class="commnet_lists border-bottom mb-2 pb-2">
        <div class="comment">
          <img class="img-fluid rounded mb-4 mb-lg-0 images" src="https://images-fe.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png" alt="..." />
          <h5>{{ item.nickname }}</h5>
        </div>
        <div>
          <p class="result-rating-rate">
            <span class="star5_rating" data-rate="{{ item.evaluation }}"></span>
            <span class="number_rating">{{ item.evaluation }}</span>
          </p>
          <div class="form-group box8">
            <h5>{{ item.title }}</h5>
          </div>
          <div class="form-group box6">
            <h6>{{ item.comment }}</h6>
          </div>
          <div class="good">
            <div class="tuuhou"></div>
            <!-- <button type="button" class="btn btn-outline-dark ">通報</button> -->
            <div>
              <a href="{% url 'bookdoor:book_comment_good' item.code %}">
              
                {% if item.count_good == 0 %}<i class="far fa-heart fa-2x"></i>
                {% else %}<i class="fas fa-heart fa-2x heart_red"></i>
                {% endif %}
                
              </a>
            </div>
            
            <h4>{{ item.good }}いいね</h4>
            
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

bookdoor/templates/bookdoor/comment_attention.html
{% extends 'bookdoor/layout.html' %}

{% block title %}Attention{% endblock %}

{% block content %}
<div>一日に3回までしか本のコメントできません</div>
<div><a href="{% url 'bookdoor:index' %}">ホームに戻る</a></div>
{% endblock %} 

bookdoor/templates/bookdoor/layout.html
{% load static %}
<!doctype>
<html lang="ja">
  <head>
    <meta charset="="utf-8>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock %}</title>

    {% block head %}{% endblock %}

    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
    href="{% static 'bookdoor/css/layout.css' %}">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body class="bg-light">
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary p-3">
      <div class="ml-md-5">
        <a class="navbar-brand navbar-dark" href="{% url 'bookdoor:index' %}">どくしょの森</a>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse mr-5" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          

          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'bookdoor:index' %}">ホーム</a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'bookdoor:book_ranking' %}">ランキング</a>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              けんさく
            </a>
            <div class="dropdown-menu " aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'bookdoor:book_search' 0 'None' %}">ほんをさがす</a>
              <a class="dropdown-item" href="{% url 'bookdoor:comment_search' 0 'None' 0 %}">コメントをさがす</a>
            </div>
              
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              アカウント
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'accounts:profile' 0 1 %}">プロフィール</a>
              <a class="dropdown-item" href="{% url 'bookdoor:favorite_book_list' 0 1 %}">お気に入りの本</a>
              <div class="dropdown-divider"></div>
              {% if request.user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'accounts:account_logout' %}">ログアウト</a>
              {% else %}
              <a class="dropdown-item" href="{% url 'accounts:account_login' %}">ログイン</a>
              <a class="dropdown-item" href="{% url 'accounts:account_signup' %}">サインアップ</a>
              {% endif %}
            </div>
          </li>
        </ul>
      </div>
    </nav>
    {% block content %}{% endblock %}

    <footer class="py-5 bg-primary">
      <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy;  dokushonomori 2021</p></div>
  </footer>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="js/scripts.js"></script>
  </body>
</html>