accounts/urls.py
from django.urls import path
from accounts import views

app_name='accounts'
urlpatterns = [
    path('profile/<int:category_id>/<int:page>', views.ProfileView.as_view(), name='profile'),
    path('login/', views.LoginView.as_view(), name='account_login'),
    path('logout/', views.LogoutView.as_view(), name='account_logout'),
    path('signup/', views.SignupView.as_view(), name='account_signup'),
    path('profile_create/', views.ProfileCreateView.as_view(), name='profile_create'),
]

bookdoor/urls.py
from django.urls import path
from . import views
from .views import BookDoorView, BookSearchView, BookCreateView
from .views import BookDetailView, BookCommentView, BookConditionView
from .views import FavoriteBookListView,BookRankingView
from .views import CommentSearchView

app_name='bookdoor'
urlpatterns=[
  path(r'',BookDoorView.as_view(), name='index'),
  path(r'book_condition/<int:category_id>/<int:age>',\
    BookConditionView.as_view(), name='book_condition'),
  path(r'book_search/<int:category_id>/<str:search>',BookSearchView.as_view(),\
     name='book_search'),
  path(r'book_detail/<str:book_code>',BookDetailView.as_view(), name='book_detail'),
  path(r'book_comment/<str:book_code>',BookCommentView.as_view(), name='book_comment'),
  path(r'book_comment_good/<str:code>',views.book_comment_good,name='book_comment_good'),
  path(r'book_comment_report/<str:code>',views.book_comment_report,\
     name='book_comment_report'),
  path(r'favorite_book/<str:code>',views.favorite_book,\
     name='favorite_book'),
  path(r'favorite_book_list/<int:category_id>/<str:search>',\
    FavoriteBookListView.as_view(),name='favorite_book_list'),
  path(r'book_ranking',BookRankingView.as_view(),name='book_ranking'),
  path(r'comment_search/<int:category_id>/<str:search>/<int:evaluation>',\
    CommentSearchView.as_view(),name='comment_search'),
  path(r'book_create',BookCreateView.as_view(), name='book_create'),
]

django_app_3/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookdoor.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth.models import UserManager,PermissionsMixin
from django.utils import timezone


class UserManager(UserManager):
  use_in_migrations=True


  def _create_user(self, username, password, **extra_fields):
    if not username:
      raise ValueError('ユーザーネームをください')
    username=self.model.normalize_username(username)
    user=self.model(username=username, **extra_fields)
    user.set_password(password)
    user.save(using=self._db)
    return user

  def create_user(self, username, password=None, **extra_fields):
    extra_fields.setdefault('is_staff',False)
    extra_fields.setdefault('is_superuser',False)
    return self._create_user(username, password, **extra_fields)

  def create_superuser(self, username, password, **extra_fields):
    extra_fields.setdefault('is_staff',True)
    extra_fields.setdefault('is_superuser',True)

    if extra_fields.get('is_staff') is not True:
      raise ValueError('Superuser must have is_staff=True.')
    if extra_fields.get('is_superuser') is not True:
      raise ValueError('Superuser must have is_superuser=True.')
    
    return self._create_user(username, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):

  username_validator = UnicodeUsernameValidator()

  username=models.CharField(
    'ユーザーネーム',
    max_length=20, 
    unique=True,
    help_text='20文字以内です',
    validators=[username_validator],
    error_messages={
      'unique': "すでに登録されているユーザーネームです"
      },
  )
  code=models.CharField('コード', max_length=10,null=True)
  birthday=models.DateField('誕生日',null=True)
  date=models.DateTimeField('入会日', default=timezone.now)
  is_staff=models.BooleanField(
    'staff status',
    default=False,
    help_text=('Designates whether the user can log into this admin site.'),
  )
  is_active=models.BooleanField(
    'active',
    default=True,
    help_text=(
      'Designates whether this user should be treated as active.'
      'Unselect this instead of deleting accounts.'
      ),
  )

  objects=UserManager()


  USERNAME_FIELD='username'
  REQUIRED_FIELDS=[]

  class Meta:
    verbose_name='user'
    verbose_name_plural='users'

class Profile(models.Model):
  owner=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
  nickname=models.CharField(max_length=20)
  choices=models.IntegerField()
  secret=models.CharField(max_length=20)
  email=models.EmailField(unique=True,null=True,blank=True)

  def __str__(self):
    return '<Profile:id='+str(self.id)+','+\
      str(self.owner)+'('+str(self.nickname)+')>'

accounts/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.db.models import fields
from allauth.account.forms import SignupForm
from .models import CustomUser, Profile
import random
import string
import datetime

class ProfileForm(forms.ModelForm):
  class Meta:
    model=Profile
    fields=['nickname','email']

class SignupUserForm(SignupForm):
  now=datetime.datetime.now()
  this_year=now.year
  years = []
  for i in range(118):
    years.append(this_year-i)

  birthday = forms.DateField( widget=forms.SelectDateWidget(years=years))
  
  def save(self, request):
    user=super(SignupUserForm,self).save(request)
    dat=string.digits + string.ascii_lowercase + string.ascii_uppercase
    while True:
      item=''.join([random.choice(dat) for i in range(10)])
      judge=CustomUser.objects.filter(code=item).count()
      if judge==0:
        break
    user.code=item
    user.birthday=self.cleaned_data['birthday']
    user.save()
    return user


class ProfileCreateForm(forms.Form):

  data=[
    (1,'はつこいのひとのなまえ'),
    (2,'はじめてみたえいが'),
    (3,'はじめてのりょこうにいったばしょ'),
    (4,'おふくろのあじといえば'),
    (5,'うまれたびょういんのなまえ'),
  ]

  nickname=forms.CharField(label='ニックネーム',max_length=20)
  choices=forms.ChoiceField(label='秘密の質問(ひみつのしつもん)',choices=data)
  secreat=forms.CharField(label='',max_length=20)
  email=forms.EmailField(label='メール',required=False)

accounts/views.py
from random import choices
from django.views import View
from django.shortcuts import render, redirect
from accounts.models import CustomUser, Profile
from bookdoor.models import BookComment
from bookdoor.models import Category
from accounts.forms import ProfileForm, SignupUserForm,ProfileCreateForm
from allauth.account import views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
import datetime

class ProfileView(LoginRequiredMixin,View):

  def __init__(self):
    self.params={
      'books':'',
      'user_data':'',
      'form': '',
      'age':'',
      'category':Category.objects.all(),
      'category_id':'',
      'page_range':'',
      'tree':'',
    }

  def get(self, request, category_id, page=1, *args, **kwargs):
    if Profile.objects.filter(owner=request.user).count()==0:
      return redirect(to='/accounts/profile_create')

    user_data=CustomUser.objects.get(id=request.user.id)
    today=datetime.date.today()
    birthday=user_data.birthday
    age=(int(today.strftime("%Y%m%d")) - int(birthday.strftime("%Y%m%d"))) // 10000
    obj=Profile.objects.get(owner=request.user.id)

    books=BookComment.objects.filter(writer=request.user)

    book=[]
    if category_id !=0:
      for item in books:
        if item.book.category_id == category_id:
          book.append(item)
    else:
      book=books

    book=Paginator(book,12)
    page_count=book.num_pages
    page_range=[]
    if page != page_count and page !=1 :
      page_range=[page-1,page,page+1]
    elif page == page_count:
      for i in range(3):
        if page-2+i >= 1:
          page_range.append(page-2+i)
    else:
      if page_count >2:
        page_range=[1,2,3]
      else:
        for i in range(page_count):
          page_range.append(i+1)
    
    if request.user.is_authenticated:
      tree=BookComment.objects.filter(writer=self.request.user).count()
      if tree<10:
        tree=1
      elif tree<20:
        tree=2
      elif tree<35:
        tree=3
      elif tree<50:
        tree=4
      elif tree<75:
        tree=5
      elif tree<100:
        tree=6
      else:
        last=BookComment.objects.filter(writer=self.request.user).last()
        today=datetime.date.today()
        ago=(int(today.strftime("%Y%m%d")) - int(last.date.strftime("%Y%m%d")))
        if ago<30:
          tree=7
        else:
          tree=8
    else:
      tree=1

    self.params['tree']=tree
    self.params['page_range']=page_range
    self.params['category_id']=category_id
    self.params['books']=book.get_page(page)
    self.params['user_data']=user_data
    self.params['form']=ProfileForm(instance=obj)
    self.params['age']=age
    return render(request, 'accounts/profile.html',self.params)

  def post(self, request, category_id, *args, **kwargs):
    obj=Profile.objects.get(owner=request.user.id)
    profile=ProfileForm(request.POST, instance=obj)
    try:

      profile.save()
    except Exception as e:
      return redirect(to='/accounts/profile/0/1')
    return redirect(to='/accounts/profile/0/1')


class LoginView(views.LoginView):
  template_name='accounts/login.html'


class LogoutView(views.LogoutView):
  template_name='accounts/logout.html'

  def post(self,*args, **kwargs):
    if self.request.user.is_authenticated:
      self.logout()
    return redirect('/')


class SignupView(views.SignupView):
  template_name='accounts/signup.html'
  form_class=SignupUserForm

class ProfileCreateView(LoginRequiredMixin,View):
  def get(self, request, *args, **kwargs):

    return render(request, 'accounts/profile_create.html', {
      'form': ProfileCreateForm,
    })

  def post(self, request, *args, **kwargs):
    profile=Profile()
    profile.owner=request.user
    profile.nickname=request.POST['nickname']
    profile.choices=request.POST['choices']
    try:

      profile.save()
    except Exception as e:
      return redirect(to='/accounts/profile_create/')
    return redirect(to='/accounts/profile/0/1')

accounts/templates/accounts/layout.html
{% load static %}
<!doctype>
<html lang="ja">
  <head>
    <meta charset="="utf-8>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock %}</title>

    {% block head %}{% endblock %}

    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/signin.css' %}">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body class="bg-light">
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary p-3">
      <div class="ml-5">
        <a class="navbar-brand navbar-dark" href="{% url 'bookdoor:index' %}">どくしょの森</a>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse mr-5" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          

          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'bookdoor:index' %}">ホーム</a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'bookdoor:book_ranking' %}">ランキング</a>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              けんさく
            </a>
            <div class="dropdown-menu " aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'bookdoor:book_search' 0 'None' %}">ほんをさがす</a>
              <a class="dropdown-item" href="{% url 'bookdoor:comment_search' 0 'None' 0 %}">コメントをさがす</a>
            </div>
              
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              アカウント
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'accounts:profile' 0 1 %}">プロフィール</a>
              <a class="dropdown-item" href="{% url 'bookdoor:favorite_book_list' 0 'None' %}">お気に入りの本</a>
              <div class="dropdown-divider"></div>
              {% if request.user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'accounts:account_logout' %}">ログアウト</a>
              {% else %}
              <a class="dropdown-item" href="{% url 'accounts:account_login' %}">ログイン</a>
              <a class="dropdown-item" href="{% url 'accounts:account_signup' %}">サインアップ</a>
              {% endif %}
            </div>
          </li>
        </ul>
      </div>
    </nav>
    {% block content %}{% endblock %}

    <footer class="py-5 bg-primary">
      <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
  </footer>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="js/scripts.js"></script>
  </body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/layout.html' %}
{% load static %}

{% block head %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta name="description" content="" />
<meta name="author" content="" />
<title>Small Business - Start Bootstrap Template</title>
<!-- Favicon-->
<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
<!-- Core theme CSS (includes Bootstrap)-->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/signin.css' %}">
{% endblock %}

{% block content %}
<div class="container login-container">
  <div class="row">
    <div class="col-md-6 offset-md-3 login-form-1">
      <h3>ログインフォーム</h3>
      <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <!-- <input type="text" class="form-control" placeholder="あなたのユーザ名" value="" /> -->
            {{ form.login }}
        </div>
        <div class="form-group">
            <!-- <input type="password" class="form-control" placeholder="あなたのパスワード" value="" /> -->
            {{ form.password }}
        </div>

        <div>
        </div>
        <div>
          <button type="submit" class="btnSubmit"> ログイン</button>
        </div>
      </form>
      <div class="form-group">
        <a href="{% url 'accounts:account_signup' %}" class="ForgetPwd">
          サインアップはこちら
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'accounts/layout.html' %}
{% load static %}

{% block head %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta name="description" content="" />
<meta name="author" content="" />
<title>Small Business - Start Bootstrap Template</title>
<!-- Favicon-->
<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
<!-- Core theme CSS (includes Bootstrap)-->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/logout.css' %}">
{% endblock %}
{% block title %}LOGOUT{% endblock %}

{% block content %}
<div class="container login-container">
  <div class="row">
    <div class="col-md-6 offset-md-3 login-form-1">
      <h5 class="aiueo">ログアウトしますか？</h5>
      
      <form method="post">
        {% csrf_token %}
        <a href="#" class="btn-square-shadow"><button type="submit">ログアウト</button></a>
        
      </form>
    </div>
  </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/layout.html' %}
{% load static %}

{% block head %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta name="description" content="" />
<meta name="author" content="" />
<title>Small Business - Start Bootstrap Template</title>
<!-- Favicon-->
<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
<!-- Core theme CSS (includes Bootstrap)-->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile.css' %}">
{% endblock %}

{% block content %}

<div class="container mb-3 bg-white pt-3">
  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary ">
    <div class="ml-5">
      <strong class="navbar-brand" >プロフィール</strong>
    </div>
  </nav>
  
  <div class="row mt-4">
    <div class="col-md-6 profile ml-md-3">
      <div class="my-md-5 flex">
        
        <h3 class="border1 txt">ユーザーネーム:</h3>
        <h3 class="border1 txt">{{ user_data.username }}</h3>
      </div>
      <div class="mb-md-5 flex">
        <h4 class="border1 txt">ねんれい：</h4>
        <h4 class="border1 txt">{{ age }}さい</h4>
      </div>
      <div class="mb-md-5 flex">
        <h5 class="txt">とうろくび：</h5>
        <h5 class="txt">{{ user_data.date }}</h5>
      </div>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <!-- <input type="password" class="form-control" placeholder="あなたのパスワード" value="" /> -->
          <strong>ニックネーム</strong>
          <div>{{ form.nickname}}</div>
        </div>
        <div class="form-group">
          <!-- <input type="password" class="form-control" placeholder="あなたのパスワード" value="" /> -->
          <strong>メールアドレス</strong>
          <div>{{ form.email }}</div>
        </div>
        <div>
          <button type="submit" class="btn btn-default btn-sm btn-primary">編集</button>
        </div>
      </form>
    </div>
    <div class="col-md-5">
      <img src="/media/{{ tree }}.jpg" class="img-fluid" alt="Responsive image">
      <h6 class="ml-4">あなたが身につけた知識や価値観は木の栄養になります</h6>
    </div>
    {% if user_data.code == 'aaaaaaaaaa' %}
    <div>
      <a href="{% url 'bookdoor:book_create' %}">本作成</a>
    </div><br>
    {% endif %}
    <div class="container mt-3 border-top pt-3">
      <div class="row">
        <div class="col-md-3">
          <div>
            <h3 class="ribbon3">今までに読んできた本</h3>
          </div>
        </div>
        <div class="btn-group col-md-1 offset-md-7 mb-4">
          <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if category_id == 0 %}
            カテゴリ
            {% else %}
            {% for item in category %}
            {% if item.id == category_id %}
            {{ item.category }}
            {% endif %}
            {% endfor %}
            {% endif %}
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'accounts:profile' 0  1 %}">すべて</a>
            {% for item in category %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:profile' item.id 1 %}">{{ item.category }}</a>
            {% endfor %}
          </div>
        </div>
        
        <div class="col-12">
          <div class="row gx-4 gx-lg-5">
            {% for item in books %}
            <div class="col-lg-2 col-md-4 col-sm-6 mb-5 position-relative flex">
              <!-- <div class="flex">
                <p></p>
                <h5 class="fav-category1">小説</h5>
              </div> -->
              <div class="card" style="width: 100%;">
                <img class="img-fluid rounded mb-4 mb-lg-0" src="https://m.media-amazon.com/images/I/417V0YU0LEL._SL500_.jpg" alt="..." />
                <div class="card-body position-static">
                  <h5>{{ item.book.title }}</h5>
                  {% if item.book.author != '' %}
                  <h6 class="fav-author">{{ item.book.author}}(著)</h6>
                  {% endif %}
                  {% if item.book.illustrator != '' %}
                  <h6 class="fav-author">{{ item.book.illustrator}}(イラスト)</h6>
                  {% endif %}
                  {% if item.book.translator != '' %}
                  <h6 class="fav-author">>{{ item.book.translator }}(翻訳)</h6>
                  {% endif %}
                  <a href="{% url 'bookdoor:book_detail' item.book.code %}" class="stretched-link"></a>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
              {% if books.has_previous %}
              <li class="page-item disabled">
                <a class="page-link" href="{% url 'accounts:profile' category_id %}{{ books.previous_page_number }}" >まえへ</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" tabindex="-1">まえへ</a>
              </li>
              {% endif %}
              {% for page_num in page_range %}
              {% if page_num == books.number %}
              <li class="page-item"><a class="page-link" tabindex="-1">{{ page_num }}</a></li>
              {% else %}
              <li class="page-item"><a class="page-link" href="{% url 'accounts:profile' category_id page_num %}">{{ page_num }}</a></li>
              {% endif %}
              {% endfor %}
              {% if books.has_previous %}
              <li class="page-item disabled">
                <a class="page-link" href="{% url 'accounts:profile' category_id %}{{ books.next_page_number }}" >つぎへ</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" tabindex="-1">つぎへ</a>
              </li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div> 
{% endblock %}

accounts/templates/accounts/profile_create.html
{% extends 'accounts/layout.html' %}

{% block title %}ProfileCreate{% endblock %}

{% block content %}
<div class="container login-container">
  <div class="row">
    <div class="col-md-6 offset-md-3 login-form-1">
      <h3>サインアップ</h3>
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <!-- <input type="text" class="form-control" placeholder="あなたのユーザ名" value="" /> -->
          <strong>ニックネーム（ひつよう）</strong>
          <div>{{ form.nickname }}</div>

        </div>
        <div class="form-group">
          <!-- <input type="text" class="form-control" placeholder="あなたのユーザ名" value="" /> -->
          <strong>秘密の質問（ひつよう）</strong>
          <div>{{ form.choices }}</div>
        </div>
        <div class="form-group">
          <!-- <input type="password" class="form-control" placeholder="あなたのパスワード" value="" /> -->
          <strong>秘密の質問の答え（ひつよう）</strong>
          <div>{{ form.secreat }}</div>
        </div>
        <div class="form-group">
          <!-- <input type="password" class="form-control" placeholder="あなたのパスワード" value="" /> -->
          <strong>メールアドレス</strong>
          <div>{{ form.email }}</div>
        </div>
        <div class="form-group">
          <button type="submit"  class="btnSubmit">サインアップ</button>
        </div>
        
      </form>
      
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'accounts/layout.html' %}
{% load static %}

{% load widget_tweaks %}

{% block head %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta name="description" content="" />
<meta name="author" content="" />
<title>Small Business - Start Bootstrap Template</title>
<!-- Favicon-->
<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
<!-- Core theme CSS (includes Bootstrap)-->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/signin.css' %}">
{% endblock %}


{% block content %}
<div class="container login-container">
  <div class="row">
    <div class="col-md-6 offset-md-3 login-form-1">
      <h3>サインアップ</h3>
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <!-- <input type="text" class="form-control" placeholder="あなたのユーザ名" value="" /> -->
          {{ form.username }}
        </div>
        <div class="form-group">
          <!-- <input type="text" class="form-control" placeholder="あなたのユーザ名" value="" /> -->
          {{ form.birthday }}
        </div>
        <div class="form-group">
          <!-- <input type="password" class="form-control" placeholder="あなたのパスワード" value="" /> -->
          {{ form.password1 }}
        </div>
        <div class="form-group">
          <!-- <input type="password" class="form-control" placeholder="あなたのパスワード" value="" /> -->
          {{ form.password2 }}
        </div>
        <div class="form-group">
          <button type="submit"  class="btnSubmit">つぎへ</button>
        </div>
        <strong>※パスワードは8文字以上</strong>
      </form>
      
    </div>
  </div>
</div>
{% endblock %}